version: '3.6'
services:  
  db:
    image: postgres
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: wubalubadubdub 
      POSTGRES_DB: cryptodb
    volumes:
      - ./db/:/var/lib/postgresql/data/
      - ./db-init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U testuser -d cryptodb" ]
      interval: 10s
      timeout: 45s
      retries: 10